sudo: required
dist: trusty

env:
  matrix:
  - CENTOS=centos:7.3.1611
  - CENTOS=centos:7.2.1511
  - CENTOS=centos:7.1.1503
  - CENTOS=centos:7.0.1406

services:
  - docker

before_install:
  - docker pull $CENTOS

script:
  - bash setup_tests.sh
