sudo: required
dist: trusty

env:
  matrix:
  - CENTOS=centos:7.3.1611 KERNEL=3.10.0-514 BUILD=7.3.1611
  - CENTOS=centos:7.2.1511 KERNEL=3.10.0-327 BUILD=7.2.1511
  - CENTOS=centos:7.1.1503 KERNEL=3.10.0-229 BUILD=7.1.1503
  - CENTOS=centos:7.0.1406 KERNEL=3.10.0-123 BUILD=7.0.1406

services:
  - docker

before_install:
  - docker pull $CENTOS
  - docker ps -a
  - docker --version

script:
  - bash setup_tests.sh
