sudo: false
dist: trusty

env:
  matrix:
  - CENTOS=centos:7.3.1611 KERNEL=3.10.0-514 BUILD=7.3.1611
  - CENTOS=centos:7.2.1511 KERNEL=3.10.0-327 BUILD=7.2.1511
  - CENTOS=centos:7.1.1503 KERNEL=3.10.0-229 BUILD=7.1.1503
  - CENTOS=centos:7.0.1406 KERNEL=3.10.0-123 BUILD=7.0.1406

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-engine
  - sudo docker pull $CENTOS
  - sudo docker run -d $CENTOS /bin/sh -c "cd /home/travis/build/chvalean/lis-next"
  - sudo docker run -d $CENTOS /bin/sh -c "bash setup_tests.sh"
  - sudo docker ps -a
  - sudo docker --version

script:
  - bash setup_tests.sh
