sudo: required
dist: trusty

env:
  matrix:
  #- CENTOS=centos:latest KERNEL=3.10.0-514.21.1
  - CENTOS=centos:7.3.1611 KERNEL=3.10.0-514
  - CENTOS=centos:7.2.1511 KERNEL=3.10.0-327
  - CENTOS=centos:7.1.1503 KERNEL=3.10.0-229
  - CENTOS=centos:7.0.1406 KERNEL=3.10.0-123

services:
  - docker

before_install:
  - docker pull $CENTOS

script:
  - bash setup_tests.sh
